---
description: "Create a provisioning template (resource: POST /api/config_templates)"
enabled: true
runner_type: "python-script"
entry_point: lib/action.py
name: config_templates.create
pack: foreman
parameters:
  operation:
    type: string
    default: config_templates.create
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  location_id:
    type: number
    required: false
    description: "Set the current location context for the request"
  organization_id:
    type: number
    required: false
    description: "Set the current organization context for the request"
  config_template:
    type: object
    required: true
    description: >
       "description: 
        parameters:
            name:
              description: template name
              required: true
              type: string
            description:
              description: ''
              required: false
              type: string
            template:
              description: ''
              required: true
              type: string
            snippet:
              description: ''
              required: false
              type: boolean
            audit_comment:
              description: ''
              required: false
              type: string
            template_kind_id:
              description: not relevant for snippet
              required: false
              type: number
            template_combinations_attributes:
              description: Array of template combinations (hostgroup_id, environment_id)
              required: false
              type: array
            operatingsystem_ids:
              description: Array of operating system IDs to associate with the template
              required: false
              type: array
            locked:
              description: Whether or not the template is locked for editing
              required: false
              type: boolean
            location_ids:
              description: REPLACE locations with given ids
              required: false
              type: array
            organization_ids:
              description: REPLACE organizations with given ids.
              required: false
              type: array
            "