---
description: "List provisioning templates per operating system (resource: GET /api/operatingsystems/:operatingsystem_id/config_templates)"
enabled: true
runner_type: "python-script"
entry_point: lib/action.py
name: operatingsystems.config_templates_index
pack: foreman
parameters:
  operation:
    type: string
    default: operatingsystems.config_templates_index
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  operatingsystem_id:
    type: string
    required: true
    description: "ID of operating system"
  location_id:
    type: number
    required: false
    description: "Scope by locations"
  organization_id:
    type: number
    required: false
    description: "Scope by organizations"
  search:
    type: string
    required: false
    description: "filter results"
  order:
    type: string
    required: false
    description: "Sort field and order, eg. ‘id DESC’"
  page:
    type: number
    required: false
    description: "Page number, starting at 1"
  per_page:
    type: number
    required: false
    description: "Number of results per page to return"